# Generated by Django 4.1 on 2023-02-28 12:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Author')),
                ('publishedDate', models.CharField(blank=True, max_length=255, verbose_name='PublishedDate')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('isbn', models.CharField(blank=True, max_length=255, verbose_name='ISBN')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='Page')),
                ('bookCover', models.ImageField(blank=True, upload_to='images/', verbose_name='BookCover')),
                ('registerDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 28, 21, 37, 29, 437702), null=True, verbose_name='RegisterDate')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='UpdateDate')),
                ('review', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
