# Generated by Django 4.1 on 2023-03-01 03:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookApp', '0002_category_language_stage_alter_book_registerdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='impression',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Impression'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='BookCover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookApp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookApp.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PublishedDate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='registerDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 12, 50, 20, 280614), null=True, verbose_name='RegisterDate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookApp.stage', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
