# Generated by Django 4.1 on 2023-03-01 03:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_book_impression_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='book',
            name='registerDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 12, 51, 45, 624092), null=True, verbose_name='RegisterDate'),
        ),
    ]
